apiVersion: v1
kind: Service
metadata:
  name: wireguard
spec:
  selector:
    app: wireguard
  type: ClusterIP
  ports:
    - name: api
      protocol: UDP
      port: 51820
      targetPort: 51820
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
  labels:
    app: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
        - name: wireguard
          image: tauplatform/wireguard:master
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 51820
          env:
            - name: LOGTAG_ENVIRONMENT
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOGTAG_APPLICATION
              value: "wireguard"
            - name: LOGTAG_VERSION
              value: "master"
            - name: LOGTAG_POD
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: LOGTAG_NODE
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          envFrom:
            - configMapRef:
                name: wireguard
          volumeMounts:
            - name: config
              mountPath: /etc/wireguard
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: wireguard
            items:
              - key: "wg0.conf"
                path: "wg0.conf"
      nodeSelector:
        software/wireguard: true
